apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-pool
  namespace: logstash
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      name: logstash-worker
      namespace: loadgen
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: 137797084791.dkr.ecr.us-east-1.amazonaws.com/loadgen/logstash:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 200m
        command: ["bin/logstash"]
        ports:
        - containerPort: 5044
